"""
Area explorer routes — bounded geographic regions (Hawaii, etc.) with all
known timeshare resorts plotted on a map.

v0: static dataset in utilities/area_data.py + static deals snapshot at
static/data/hawaii_deals.json (regenerated by scripts/scrape_redweek.py).
Future: backed by crab.area_resorts + crab.redweek_observations.
"""
import json
import os

from flask import Blueprint, render_template, abort, current_app

from utilities.area_data import AREAS

bp = Blueprint('area', __name__)


def _load_deals_snapshot(slug):
    """Load the latest deals snapshot for an area, if one exists."""
    path = os.path.join(current_app.static_folder, 'data', f'{slug}_deals.json')
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _load_synthesis(slug):
    """Pull latest synthesis row per resort for this area.
    Returns {resort_pid: {summary_json, model, n_observations, computed_at}}.
    """
    from utilities.postgres_utils import get_db_connection
    import psycopg2.extras
    out = {}
    try:
        conn = get_db_connection()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute("""
            SELECT DISTINCT ON (resort_pid)
              resort_pid, summary_json, model, n_observations,
              to_char(computed_at, 'YYYY-MM-DD"T"HH24:MI:SS') AS computed_at
            FROM crab.area_synthesis
            WHERE area_slug = %s
            ORDER BY resort_pid, computed_at DESC
        """, (slug,))
        for row in cur.fetchall():
            out[row['resort_pid']] = dict(row)
        conn.close()
    except Exception:
        pass
    return out


@bp.route('/area/<slug>')
def area_explore(slug):
    area = AREAS.get(slug)
    if not area:
        abort(404)
    # Attach synthesis to each resort that has one
    synthesis_by_pid = _load_synthesis(slug)
    enriched_resorts = []
    for r in area['resorts']:
        if r['pid'] in synthesis_by_pid:
            r = {**r, 'synthesis': synthesis_by_pid[r['pid']]}
        enriched_resorts.append(r)
    area = {**area, 'resorts': enriched_resorts}
    # Per-island stats for the legend
    by_island = {}
    for r in area['resorts']:
        by_island.setdefault(r['island'], []).append(r)
    island_stats = [
        {
            'island': island,
            'count': len(resorts),
            'color': area['island_colors'].get(island, '#888'),
            'rated_count': sum(1 for r in resorts if r.get('rating')),
            'synth_count': sum(1 for r in resorts if r.get('synthesis')),
        }
        for island, resorts in sorted(by_island.items(), key=lambda x: -len(x[1]))
    ]
    deals_snapshot = _load_deals_snapshot(slug)
    return render_template(
        'area/explore.html',
        area=area,
        island_stats=island_stats,
        deals_snapshot=deals_snapshot,
        synthesis_count=len(synthesis_by_pid),
        active_page=None,
    )
